---
title: "Exam 2"
format: html
---

```{r}
library(tidytuesdayR)
library(tidyverse)
library(rnaturalearth)
library(sf)

tuesdata <- tt_load('2020-02-18')
fc <- tuesdata$food_consumption

str(fc)
head(fc, 22)
```
```{r}
# Inspect country variable: The dataframe contains information about 130 countries

fc |>
  count(country)

# Inspect food_category variable 
fc |>
  select(food_category)

# Fix food_category variable 

fc <- fc |>
  mutate(food_category = fct_recode(food_category,
                                    "Lamb" = "Lamb & Goat",
                                    "Dairy" = "Milk - inc. cheese",
                                    "Wheat" = "Wheat and Wheat Products",
                                    "Nuts" = "Nuts inc. Peanut Butter"))

```
::: {.callout-note title="Research Question 1"}

Which 5 countries consume the most food are?

 - Show the answer as a 2-column table and as graph.
 - Sort the countries based on consumption from largest to smallest 
 - Use the cleaned dataframe
 
:::

```{r}

```


